Improving Notification Behavior
ruif3r/COVID-19-Tracking pull request #12
Opened 2020-08-20 18:19 UTC by ruif3r

# Description

Modified notification behavior by changing the service class for a worker class and an actual notification.

# ChangeType

Improving

# Steps to Test

Open the app

2020-08-23 09:50 UTC, jinmyjbv requested changes

2020-08-23 09:50 UTC, jinmyjbv commented on app/src/main/java/com/example/ncov19traking/BaseApp.kt
> +            PeriodicWorkRequestBuilder<NotificationWorker>(11, TimeUnit.HOURS).build()
this `11` could be in a constant.

2020-09-23 17:27 UTC, jinmyjbv requested changes

2020-09-23 17:27 UTC, jinmyjbv commented on app/src/main/java/com/example/ncov19traking/NotificationWorker.kt
> +            .setAutoCancel(true)
you should separate all the building of the `builder` in a separate method.

2020-09-23 17:27 UTC, jinmyjbv commented on app/src/main/java/com/example/ncov19traking/NotificationWorker.kt
> +    }
split this huge method into small readable methods.

2020-09-23 17:27 UTC, jinmyjbv commented on build.gradle
> +    ext.kotlin_version = '1.3.72'
you could do the same you are doing for the kotlin version to all your gradle dependencies versions.

2020-09-23 17:28 UTC, jinmyjbv commented
For some reason the notification is not showing for me even if I change the code to 10 seconds for the worker

2020-09-24 00:00 UTC, ruif3r commented
thats because the minimun amount of time to execute an operation that workManager allows is 15 minutes

2020-09-26 18:48 UTC, jinmyjbv approved these changes

2020-09-26 18:48 UTC, merged