[22]Database crash when tables are empty
ruif3r/COVID-19-Tracking pull request #2
Opened 2020-04-22 05:34 UTC by ruif3r

# Description

Fixed database crash when accessing to an empty table by:
- Adding Count Query to all daos
- Adding methods in NCoVRepository to check if tables are empty or not

Other minor changes in class and package names

# Change Type

bug fix

# Steps to Test

Open the app for the very first time without wifi access nor mobile network

2020-05-07 19:33 UTC, jinmyjbv requested changes

2020-05-07 19:33 UTC, jinmyjbv commented on app/src/main/java/com/example/ncov19traking/ui/graphs/GraphsFragment.kt
>          chart.animateX(2000)
el metodo `onCreateView()` tiene muchas responsabilidades y es muy largo, deberias extraer algunas cosas a otros metodos.

2020-05-07 19:33 UTC, jinmyjbv commented on app/src/main/java/com/example/ncov19traking/ui/graphs/GraphsFragment.kt
> +                        "Global Cases",
los strings no deberian estar quemados, deberian guardarse en un archivo `strings`

2020-05-07 19:33 UTC, jinmyjbv commented on app/src/main/java/com/example/ncov19traking/ui/graphs/GraphsFragment.kt
> +                        "#6200EE"
lo mismo de arriba pero en un archivo `colors`

2020-05-07 19:33 UTC, jinmyjbv commented on app/src/main/java/com/example/ncov19traking/ui/graphs/GraphsFragment.kt
> +        chart.axisLeft.textColor = Color.parseColor("#9E9E9E")
este setUp de chart deberia estar en otro metodo

2020-05-07 19:33 UTC, jinmyjbv commented on app/src/main/java/com/example/ncov19traking/daos/CountryDao.kt
> +    fun getCountryCount(): Int
creo que esta llamada a la base de datos te la puedes ahorrar, usualmente las llamadas a la base de datos son costosas y creo que esta cuenta la puedes hacer en la app con la informacion que obtienes de `load()` lo mismo aplica para todos los `COUNT(*)` . Si igual vas a hacer un `SELECT *` en la misma tabla puedes usar `Array.size` para saber la cantidad de `NumbersByCountry` que tienes.

2020-05-07 19:33 UTC, jinmyjbv commented on app/src/main/java/com/example/ncov19traking/data/NCoVRepository.kt
> +                nCoVDao.load()
creo que seria mejor tener un tryCatch en el dao en el metodo `load()` asi evitamos hacer dos llamadas a la base de datos solo para comprobar que no esta vacía

2020-05-09 18:17 UTC, ruif3r commented on app/src/main/java/com/example/ncov19traking/daos/CountryDao.kt
> +    fun getCountryCount(): Int
deleted

2020-05-09 18:17 UTC, ruif3r commented on app/src/main/java/com/example/ncov19traking/data/NCoVRepository.kt
> +                nCoVDao.load()
fixed

2020-05-09 18:17 UTC, ruif3r commented on app/src/main/java/com/example/ncov19traking/ui/graphs/GraphsFragment.kt
> +        chart.axisLeft.textColor = Color.parseColor("#9E9E9E")
done

2020-05-09 18:17 UTC, ruif3r commented on app/src/main/java/com/example/ncov19traking/ui/graphs/GraphsFragment.kt
> +                        "#6200EE"
done

2020-05-09 18:17 UTC, ruif3r commented on app/src/main/java/com/example/ncov19traking/ui/graphs/GraphsFragment.kt
> +                        "Global Cases",
done

2020-05-10 19:24 UTC, jinmyjbv approved these changes

2020-05-10 19:24 UTC, merged